### ISSUE TITLE
When launching the app, "folders" and "notes" are undefined

### ISSUE THREAD

**Issue by gurguven** [moki-moki/web-obsi#2]
components\sidebar\sidebar.tsx (94:28) @ mapTypeError: Cannot read properties of undefined (reading 'map')
![image](https://github.com/user-attachments/assets/56fb517a-ba49-4fc6-9e62-473e474d77a7)

Fixed with a ? before .map: 
![image](https://github.com/user-attachments/assets/0ee855f3-108e-436f-a7bb-217e141fc7d1)

![image](https://github.com/user-attachments/assets/fe0c3133-682d-40ca-8b41-85c17de73293)

**Comment by moki-moki** [comment]
Hi @gurguven ,

Thanks for pointing that out. I've tried it on my local machine and it worked perfectly. However, I've added the fix you mentioned just in case.

**Comment by moki-moki** [comment]
Hi

**Comment by moki-moki** [comment]
Hi @gurguven ,

Thanks for pointing that out. I've tried to replicate it on my local machine, but didn't succeed. However, I've put your fix as you mentioned just in case.

**Comment by moki-moki** [comment]
I figured out what was the bug, the docker didn't connect correctly with my ORM and DB. Since on my machine I've already had database created, and had a fresh build of dev.db, all the functionality was working. Since then, I pushed a new release that fixed this and [this ](https://github.com/moki-moki/web-obsi/issues/1) issue.
